blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/AppOutlet/GetDisCorkie/discussions/categories/feature-request
    about: Please ask and answer questions here.
    