blank_issues_enabled: false
contact_links:
  - name: Other
    url: https://github.com/AppOutlet/GetDisCorkie/discussions
    about: For suggestions, support and other questions, please use the Discusions
    